# Generated by Django 2.1.5 on 2019-02-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='familyName',
            field=models.CharField(default='null', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='givenName',
            field=models.CharField(default='null', max_length=150),
            preserve_default=False,
        ),
    ]
